### ISSUE TITLE
Module should have a testsuite

### ISSUE THREAD

**Issue by kbakk** [bobbui/json-logging-python#15]
The module is currently missing a testsuite. I propose to use [pytest](https://docs.pytest.org/en/latest/).

Let me know if you are interested in a PR that includes a couple of tests. 

It would be nice to have an automated build and test pipeline (perhaps with Travis CI) as well.

**Comment by thangbn** [comment]
hey @kbakk thanks for that, i couldn't agree more with you. PR is welcome.

**Comment by nickma82** [comment]
Took me a while to figure out how to test this module E2E.. 
https://github.com/thangbn/json-logging-python/pull/54/files#diff-698b62a2f2ddc82593789aa186220475R71-R123
