### ISSUE TITLE
Unhelpful warning

### ISSUE THREAD

**Issue by npotts** [bobbui/json-logging-python#55]
I import json_logging, which is useful when deployed (ELK and all that), but on local development, it is a royal PITA, so I purposefully set `ENABLE_JSON_LOGGING=False`.

I eventually get this warning

 https://github.com/bobbui/json-logging-python/blob/master/json_logging/__init__.py#L143-L145

Which is neither helpful, wrong, nor right.  I'm generally not fond of no-op logging message like this, but It does have some utility the first time or two you setup the library.

All that said:

* How can I disable this warning when I need to
* Is there another obvious workaround I should be using:

**Comment by bobbui** [comment]
hi,
I understand your frustration, but it will definitely useful for first-time users.
a quick way to disable it is
```python
json_logging._logger.disabled = True
json_logging.init_<fw name>
```
