### ISSUE TITLE
docs: logging.getLogger('root') does not get you the root logger

### ISSUE THREAD

**Issue by howardjones** [bobbui/json-logging-python#56]
In the README, it says to use `logging.getLogger('root')` to initialise the root logger. That doesn't do that. That initialises a logger called "root".`logging.getLogger(None)` gets you the root logger.

(Just spent a while with `logging_tree` to figure out why I couldn't getting JSON logging working in non-main modules)

**Comment by bobbui** [comment]
will take a lôk

**Comment by bobbui** [comment]
updated docs thanks!
