### ISSUE TITLE
Trivial issue

### ISSUE THREAD

**Issue by zeroaltitude** [bobbui/json-logging-python#57]
https://github.com/bobbui/json-logging-python/blob/8fa8f232aebd0ab1a5189c5d1e4f7d8c91f9addc/json_logging/__init__.py#L144

"enabled" -- small fix, but makes the package seem more serious when it doesn't have grammatical issues.

**Comment by bobbui** [comment]
thanks, i will update it

**Comment by bobbui** [comment]
fixed on 1.2.7
