### ISSUE TITLE
Can I SET the correlation_id (in non-http context)?

### ISSUE THREAD

**Issue by howardjones** [bobbui/json-logging-python#69]
I have a process that listens for MQ events from elsewhere, and makes API requests based on them. We are looking at adding correlation_id to the MQ event data (they did ultimately originate from a HTTP request) but can I *set* the correlation_id in my MQ listener, so that its logs contain it and so that the API calls can use it?

**Comment by bobbui** [comment]
@howardjones Updated the docs to explain how to manually set the correlation id: https://github.com/bobbui/json-logging-python#forced-overriding-correlation-id
