### ISSUE TITLE
Feature request - Pass all extra properties into the log

### ISSUE THREAD

**Issue by uda** [bobbui/json-logging-python#77]
we switched from `json-lgging-py` to this, and we already have many logs writing like this:
```python
logger.info('Something happened', extra={"correlation_id": correlation_id, "tags": ["app:name"]})
```

Switching to `json-logging` we lost those data points until i read again the docs about logging `extra` details.

Personally I think this complicates things and can be simplified, I am going to do it any way for our usage, but want to know if this contribution back is wanted (with backwards compatibility for users of `json-logging`), with optional precedence of `props` over direct properties or the other way around.

**Comment by bobbui** [comment]
contribution is welcomed
