### ISSUE TITLE
Failed to customize Procedure

### ISSUE THREAD

**Issue by hanzhenbjm** [bobbui/json-logging-python#83]
`class TestLog(json_logging.JSONLogWebFormatter):
    def _format_log_object(self, record, request_util):

        json_log_object = super(TestLog, self)._format_log_object(record, request_util)
        json_log_object.update({
            "message": _sanitize_log_msg(record),
            "lineno": record.lineno,
            "TraceId": request_util.get_correlation_id(within_formatter=True),
            "log_type": "desc"
        })

        return json_log_object`

use flask web framework, 

Failed to customize Procedure

{"written_ts": 1630401382592000000, "thread": "Thread-2", "level": "DEBUG", "line_no": 30, "module": "main", "correlation_id": "1c030c00-0a3c-11ec-a078-aced5c5e9c18", "msg": "ok=123", "logger": "test-logger", "type": "log", "written_at": "2021-08-31T09:16:22.592Z"}
There's nothing I added

**Comment by hanzhenbjm** [comment]
![image](https://user-images.githubusercontent.com/33510155/131478353-2408d0e7-a3a8-41d9-b0a9-aa3257e12b36.png)
![image](https://user-images.githubusercontent.com/33510155/131478387-36f89e3d-80c0-4673-9ded-4845235ab9ad.png)
and What this function does （RequestResponseDTOBase）
thanks

**Comment by bobbui** [comment]
can u provide your full source code

**Comment by hanzhenbjm** [comment]
[main.zip](https://github.com/bobbui/json-logging-python/files/7209370/main.zip)

**Comment by hanzhenbjm** [comment]
class a(json_logging.formatters.JSONLogFormatter):
    def _format_log_object(self, record, request_util):
        json_log_object = super(a, self)._format_log_object(record, request_util)
        json_log_object.update({
            "code_message": record
        })
        return json_log_object

**Comment by hanzhenbjm** [comment]
`class a(json_logging.formatters.JSONLogFormatter):
    def _format_log_object(self, record, request_util):
        json_log_object = super(a, self)._format_log_object(record, request_util)
        json_log_object.update({
            "code_message": record
        })
        return json_log_object
`
